use_frameworks!

target 'AIOFassPaySDK_Example' do
  pod 'AIOFassPaySDK', :path => '../'

  target 'AIOFassPaySDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
